# Generated by Django 5.1.5 on 2025-03-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('responsibility_center', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('last_date_modified', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
