# Generated by Django 5.1.5 on 2025-03-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='county',
            new_name='County',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='customer_status',
            new_name='Customer_Status',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='last_date_modified',
            new_name='Last_Date_Modified',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='no',
            new_name='No',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='responsibility_center',
            new_name='Responsibility_Center',
        ),
        migrations.RenameField(
            model_name='temporarycustomer',
            old_name='vat_registration_no',
            new_name='VAT_Registration_No',
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=255)),
                ('power', models.CharField(max_length=50)),
                ('primary_voltage', models.CharField(max_length=50)),
                ('secondary_voltage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('oil_heating', models.CharField(max_length=50)),
                ('conductor_heating', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.temporarycustomer')),
            ],
        ),
    ]
