# Generated by Django 5.1.5 on 2025-03-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_county_temporarycustomer_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='customer_no',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.temporarycustomer'),
        ),
    ]
