# Generated by Django 5.1.5 on 2025-03-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customerrequest_customer_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.temporarycustomer'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
