# Generated by Django 5.1.5 on 2025-03-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customerrequest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='customer_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.temporarycustomer'),
        ),
        migrations.AlterField(
            model_name='customerrequest',
            name='customer_no',
            field=models.CharField(max_length=50),
        ),
    ]
