# Generated by Django 5.1.5 on 2025-04-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customerrequest_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(max_length=100)),
                ('objet', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('client_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('sent_to_cost_responsible', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedBomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('designation', models.TextField()),
                ('unite', models.CharField(max_length=20)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarque', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.savedbom')),
            ],
        ),
    ]
