# Generated by Django 5.1.5 on 2025-04-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_savedbom_date_savedbom_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedbom',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomenclature', to='core.customerrequest'),
        ),
    ]
