# Generated by Django 5.1.5 on 2025-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedbom_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbom',
            name='sent_to_cost_responsible',
            field=models.BooleanField(default=True),
        ),
    ]
