# Generated by Django 5.1.5 on 2025-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_savedbom_sent_to_cost_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedbom',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('emise', 'Émise')], default='en_cours', max_length=20),
        ),
    ]
