# Generated by Django 5.1.5 on 2025-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_savedbom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
