# Generated by Django 5.1.5 on 2025-05-19 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customerrequest_validated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='description_file',
            field=models.FileField(blank=True, help_text='Fichier joint (PDF ou image)', null=True, upload_to='descriptions/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='description_text',
            field=models.TextField(blank=True, help_text='Description facultative de la demande', null=True),
        ),
    ]
