# Generated by Django 5.1.5 on 2025-04-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_phone_number_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Ex : Rue de la Liberté, Tunis', null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Format attendu : exemple@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Inclure l’indicatif pays. Ex : +21699123456', max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('ResponsableEtude', 'ResponsableEtude'), ('ResponsableCout', 'ResponsableCout')], max_length=30, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame')], max_length=10, null=True, verbose_name='Titre'),
        ),
    ]
